### ISSUE TITLE
pusher:error

### ISSUE THREAD

**Issue by SaidalievSSh** [Safemood/soketi-docker-compose#2]
Hello, I installed soketi and I use it, everything is fine, I decided to install it on docker for some reason, it does not work. ssl proxy is configured, when I use curl or browser I get ok, in the browser on the WS tab "{
   "event": "pusher:error",
   data: {
     code: 4001
     "message": "App key FFKLJSSKL KLBNKFGJOWBB does not exist."
   }
}". Can you tell me what could be the problem?
i use image quay.io/soketi/soketi:1.4-16-debian

**Comment by drjoju** [comment]
Hi, I kown is to late, but I have the same error and I found a solution. As far as I see, the App Key, Id and Secret are fixed for array configuration and can't be modified (Looking into the docker source code). The solution is to use an external "database" for the apps like Redis.

This can be a posible docker solution for your problem:

```
version: '3.9'
services:

  soketi:
    container_name: 'soketi_server'
    restart: unless-stopped
    image: 'quay.io/soketi/soketi:1.4-16-debian'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    depends_on:
      - redis
    links:
      - redis
    environment:
      - SOKETI_DEBUG='${DEBUG:-1}'
      - SOKETI_METRICS_SERVER_PORT=${METRICS_SERVER_PORT-9601}
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
      - SOKETI_APP_ENABLE_CLIENT_MESSAGES=${SOKETI_APP_ENABLE_CLIENT_MESSAGES-false}
    networks:
      - soketi_frontend
      - soketi_backend
    restart: unless-stopped

  redis:
    image: redis
    networks:
      - soketi_backend
    restart: unless-stopped

networks:
  soketi_frontend:
    driver: bridge
  soketi_backend:
    driver: bridge
````

I think I have a problem with SOKETI_APP_ENABLE_CLIENT_MESSAGES but this is a minor problem that can be solved.

Best regards

**Comment by drjoju** [comment]
Here it is the full code working with whisper too

```
version: '3.9'
services:

  soketi:
    container_name: 'soketi_server'
    restart: unless-stopped
    image: 'quay.io/soketi/soketi:1.4-16-debian'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    depends_on:
      - redis
    links:
      - redis
    environment:
      - SOKETI_DEBUG='${DEBUG:-1}'
      - SOKETI_METRICS_SERVER_PORT=${METRICS_SERVER_PORT:-9601}
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
      - SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES:-false}
    networks:
      - soketi_frontend
      - soketi_backend
    restart: unless-stopped

  redis:
    image: redis
    networks:
      - soketi_backend
    restart: unless-stopped

networks:
  soketi_frontend:
    driver: bridge
  soketi_backend:
    driver: bridge

```

You can use a .env like 

```
SOKETI_PORT=6001
SOKETI_METRICS_SERVER_PORT=9601
DEBUG=1
PUSHER_APP_ID=name_of_app
PUSHER_APP_KEY=f0fo3PxDfynr0p
PUSHER_APP_SECRET=sWw8i8KyOE
PUSHER_PORT=6001
DEFAULT_APP_ENABLE_CLIENT_MESSAGES=true # make true if you want to enable client events
```

Best regards
